services:
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    image: !reset null
    pull_policy: !reset null
    build:
      context: frontend
      target: prod
      args:
        NEXT_PUBLIC_BASE_URL: https://caviardeul.local

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    image: !reset null
    pull_policy: !reset null
    build:
      context: backend
      target: prod

  worker:
    extends:
      file: docker-compose.yml
      service: worker
    image: !reset null
    pull_policy: !reset null
    build:
      context: backend
      target: prod

  scheduler:
    extends:
      service: worker
    command: taskiq scheduler worker:scheduler

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    pull_policy: !reset null
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    pull_policy: !reset null
    ports:
      - "127.0.0.1:6379:6379"

networks:
  db_network:
  nginx_network:

volumes:
  dbdata:
  staticdata:
