# Generated by Django 5.0.2 on 2024-02-17 16:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyArticleScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("nb_attempts", models.PositiveIntegerField()),
                ("nb_correct", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=256)),
                ("page_name", models.CharField(max_length=256)),
                ("nb_winners", models.PositiveIntegerField()),
                ("stats", models.JSONField()),
                ("public_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "safety",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("unsafe", "Unsafe"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=256)),
                ("page_name", models.CharField(max_length=256)),
                ("nb_winners", models.PositiveIntegerField()),
                ("stats", models.JSONField()),
                ("date", models.DateTimeField()),
                ("nb_daily_winners", models.PositiveIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(models.F("date"), name="daily_article_date_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyarticle",
            constraint=models.UniqueConstraint(
                models.F("date"), name="daily_article_date_unq"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyarticle",
            constraint=models.UniqueConstraint(
                models.F("page_id"), name="daily_article_page_id_unq"
            ),
        ),
        migrations.AddField(
            model_name="dailyarticlescore",
            name="daily_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="caviardeul.dailyarticle",
            ),
        ),
        migrations.AddField(
            model_name="dailyarticlescore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="customarticle",
            index=models.Index(
                models.F("public_id"), name="custom_article_public_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customarticle",
            constraint=models.UniqueConstraint(
                models.F("page_id"),
                models.F("created_by"),
                name="custom_article_page_id_creator_unq",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyarticlescore",
            constraint=models.UniqueConstraint(
                models.F("daily_article"),
                models.F("user"),
                name="daily_article_score_user_unq",
            ),
        ),
    ]
