# Generated by Django 5.0.2 on 2024-04-01 12:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyArticleScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("nb_attempts", models.PositiveIntegerField()),
                ("nb_correct", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=256)),
                ("page_name", models.CharField(max_length=256)),
                ("nb_winners", models.PositiveIntegerField()),
                ("stats", models.JSONField()),
                ("public_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "safety",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("unsafe", "Unsafe"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=256)),
                ("page_name", models.CharField(max_length=256)),
                ("nb_winners", models.PositiveIntegerField()),
                ("stats", models.JSONField()),
                ("date", models.DateTimeField()),
                ("nb_daily_winners", models.PositiveIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(models.F("date"), name="daily_article_date_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyarticle",
            constraint=models.UniqueConstraint(
                models.F("date"), name="daily_article_date_unq"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyarticle",
            constraint=models.UniqueConstraint(
                models.F("page_id"), name="daily_article_page_id_unq"
            ),
        ),
        migrations.AddField(
            model_name="dailyarticlescore",
            name="daily_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="caviardeul.dailyarticle",
            ),
        ),
        migrations.AddField(
            model_name="dailyarticlescore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="customarticle",
            index=models.Index(
                models.F("public_id"), name="custom_article_public_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customarticle",
            constraint=models.UniqueConstraint(
                models.F("page_id"),
                models.F("created_by"),
                name="custom_article_page_id_creator_unq",
            ),
        ),
        migrations.AddConstraint(
            model_name="customarticle",
            constraint=models.UniqueConstraint(
                models.F("public_id"), name="custom_article_public_id_unq"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyarticlescore",
            constraint=models.UniqueConstraint(
                models.F("daily_article"),
                models.F("user"),
                name="daily_article_score_user_unq",
            ),
        ),
    ]
