# Generated by Django 5.0.7 on 2024-07-13 17:49

from django.db import migrations, models

from caviardeul.services.score import compute_median_from_distribution


def migrate_model(model):
    articles = []
    for article in model.objects.select_for_update():
        distribution = article.stats.get("distribution", {})
        article.median = compute_median_from_distribution(distribution)
        articles.append(article)
    model.objects.bulk_update(articles, fields=["median"])


def forward(apps, _):
    migrate_model(apps.get_model("caviardeul", "CustomArticle"))
    migrate_model(apps.get_model("caviardeul", "DailyArticle"))


class Migration(migrations.Migration):
    dependencies = [
        ("caviardeul", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customarticle",
            name="median",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyarticle",
            name="median",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(forward, migrations.RunPython.noop, elidable=True),
    ]
