# Generated by Django 5.2.10 on 2026-01-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caviardeul", "0002_median"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyarticle",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="dailyarticle",
            index=models.Index(
                models.F("last_checked_at"), name="daily_article_last_check_idx"
            ),
        ),
    ]
