# Generated by Django 6.0.1 on 2026-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caviardeul", "0003_dailyarticle_last_checked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customarticle",
            name="stats",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailyarticle",
            name="stats",
            field=models.JSONField(blank=True),
        ),
    ]
