name: Crontab
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call admin API endpoint
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer $ADMIN_TOKEN" https://caviardeul.fr/api/admin/cleaner
